"""entries table

Revision ID: 02dfe77e1238
Revises: 
Create Date: 2019-02-17 16:57:06.113921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02dfe77e1238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('header', sa.String(length=20), nullable=False),
    sa.Column('unique_id', sa.String(length=60), nullable=True),
    sa.Column('signature', sa.String(length=10), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_entry_body'), 'entry', ['body'], unique=False)
    op.create_index(op.f('ix_entry_header'), 'entry', ['header'], unique=False)
    op.create_index(op.f('ix_entry_signature'), 'entry', ['signature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_signature'), table_name='entry')
    op.drop_index(op.f('ix_entry_header'), table_name='entry')
    op.drop_index(op.f('ix_entry_body'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
