"""realty table

Revision ID: 8e578129341e
Revises: 
Create Date: 2019-03-05 21:28:35.314151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e578129341e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oblast_district', sa.String(length=100), nullable=False),
    sa.Column('settlement', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('under_construction', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('premise_ares', sa.Float(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('construction_year', sa.Integer(), nullable=True),
    sa.Column('rooms_number', sa.Integer(), nullable=True),
    sa.Column('premise_area', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flat_location_id'), 'flat', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flat_location_id'), table_name='flat')
    op.drop_table('flat')
    op.drop_table('location')
    # ### end Alembic commands ###
